
###Create New User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "abz@ayvc.com",
    "password": "alR5"
}


### Signin user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "abc@ayvc.com",
    "password": "alR52"
}


### Find a particular user with a given ID
GET http://localhost:3000/auth/3

### Find all users with a given email
GET http://localhost:3000/auth

### Delete a user given id
DELETE http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "password": "123a-fg"
}

### Set a color  
GET http://localhost:3000/auth/color/blue

### Get the color
GET http://localhost:3000/auth/colors
